name: Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run test with coverage
        run: make coverage

      - uses: javanile/lcov-sh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
